### ISSUE TITLE
Is this array name a typo?

### ISSUE THREAD

**Issue by merijn** [nlesc-smcm/i-emic#123]
Judging by the surrounding code this should probably be setting `dfzW`, rather than `dfzw`?

https://github.com/nlesc-smcm/i-emic/blob/19433763d29522f31904cd239798277164452dab/src/ocean/grid.F90#L50-L53

**Comment by merijn** [comment]
@sbte @erik808

**Comment by Sbte** [comment]
ForTRan Is CAsE insEnSitIVE.
