### ISSUE TITLE
Add macOS to the Travis build matrix

### ISSUE THREAD

**Issue by Sbte** [nlesc-smcm/i-emic#34]

**Comment by merijn** [comment]
hmm, apparently I don't have access to assign tickets in nlesc-smcm to myself?

**Comment by Sbte** [comment]
I gave you write access, so now you should be able to

**Comment by Sbte** [comment]
If it is easier to do this using some other CI service like Azure Pipelines or a dedicated NLeSc service, then feel free to do so by the way

**Comment by merijn** [comment]
Fixed!
