### ISSUE TITLE
Did the `minimum desired Newton iterations` parameter get renamed to `minimum Newton iterations`?

### ISSUE THREAD

**Issue by merijn** [nlesc-smcm/i-emic#69]
The former appears in some parameter files, but doesn't seem to be in the code? Did it get renamed?

**Comment by Sbte** [comment]
```
transient/AdaptiveTransient.H:61:    min_wanted_newton_steps_(params->get("minimum desired Newton iterations", 3)), 
transient/AdaptiveTransient.H:62:    max_wanted_newton_steps_(params->get("maximum desired Newton iterations", 3)),
```

**Comment by merijn** [comment]
I'm finding them in the continuation parameter XML, though?

**Comment by Sbte** [comment]
In that case it got renamed I suppose:

```
continuation/Continuation.H:34:    maxNewtonIterations_   (pars->get("maximum Newton iterations", 7)),
continuation/Continuation.H:35:    minNewtonIterations_   (pars->get("minimum Newton iterations", 1)),
```

**Comment by merijn** [comment]
Yeah, that's what I guessed, but I wasn't sure of the continuation parameters also got used in other places.

**Comment by erik808** [comment]
I think I did that. There are ancient xml files lying around. You can only
trust the source code for correct naming.

**Comment by Sbte** [comment]
Even more reason for removing all default parameters from the xml files.

**Comment by Sbte** [comment]
I think this can be closed as Continuation parameters are now validated.
